version: '3.8'

services:
  api:
    restart: always
    build:
      context: ./api
    env_file:
      - .env
    depends_on:
      - redis
    expose:
      - "8000"
      - "6379"
    networks:
      fbnet:
        ipv4_address: 172.19.0.2

  frontend:
    restart: always
    build:
      context: ./frontend
    env_file:
      - .env
    depends_on:
      - api
    expose:
      - "8000"
    networks:
      fbnet:
        ipv4_address: 172.19.0.3
    
  parser:
    restart: always
    build:
      context: ./parser
    env_file:
      - .env
    depends_on:
      - api
    expose:
      - "8000"
    networks:
      fbnet:
        ipv4_address: 172.19.0.4

  redis:
    restart: always
    build:
      context: ./redis
    env_file:
      - .env
    volumes:
      - ./backup:/backup
    expose:
      - "6379"
    networks:
      fbnet:
        ipv4_address: 172.19.0.5
        aliases:
          - api

networks:
  fbnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16
