version: '3.8'

services:
  api:
    restart: always
    build:
      context: ./api
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - my-network

  frontend:
    restart: always
    build:
      context: ./frontend
    env_file:
      - .env
    depends_on:
      - api
    networks:
      - my-network

  parser:
    restart: always
    build:
      context: ./parser
    env_file:
      - .env
    depends_on:
      - api
    networks:
      - my-network
    # ports:
    #   - 80:80
    #   - 433:433

  redis:
    restart: always
    build:
      context: ./redis
    env_file:
      - .env
    volumes:
      - ./backup:/backup
    command: sleep infinity
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
