services:
  api:
    build:
      context: ./api
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
    restart: always

  frontend:
    build:
      context: ./frontend
    env_file:
      - .env
    depends_on:
      - api
    restart: always

  parser:
    build:
      context: ./parser
    env_file:
      - .env
    depends_on:
      - api
    restart: always

  redis:
    build:
      context: ./redis
    env_file:
      - .env
    volumes:
      - ./backup:/backup
    restart: always
