name: Deploy to Server 2

on:
  push:
    branches:
      - develop
      - all-testing

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

    - name: Copy files to server
      run: rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./ ${{ secrets.DEPLOY_SERVER_USER }}@${{ secrets.DEPLOY_HOST_SERVER }}:/deploy_campus_bot

    - name: Run Docker Compose
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.DEPLOY_SERVER_USER }}@${{ secrets.DEPLOY_HOST_SERVER }} << 'EOF'
          cd /deploy_campus_bot
          docker-compose down
          docker-compose up -d --build
        EOF
 