name: Deploy to Server

on:
  push:
    branches:
      - develop
      - all-testing

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Copy environment variables to .env file
      run: |
        echo BOT_API_TOKEN=${{ secrets.BOT_API_TOKEN }} >> .env
        echo BOT_TOKEN=${{ secrets.BOT_TOKEN }} >> .env
        echo DOCKER_HUB_LOGIN=${{ secrets.DOCKER_HUB_LOGIN }} >> .env
        echo DOCKER_HUB_PASSWORD=${{ secrets.DOCKER_HUB_PASSWORD }} >> .env
        echo EDU_SCHOOL_LOGIN=${{ secrets.EDU_SCHOOL_LOGIN }} >> .env
        echo EDU_SCHOOL_PASSWORD=${{ secrets.EDU_SCHOOL_PASSWORD }} >> .env
        echo API_ADDRESS=${{ secrets.API_ADDRESS }} >> .env
        echo API_PORT=${{ secrets.API_PORT }} >> .env
        echo REDIS_DB=${{ secrets.REDIS_DB }} >> .env
        echo REDIS_HOST=${{ secrets.REDIS_HOST }} >> .env
        echo REDIS_PORT=${{ secrets.REDIS_PORT }} >> .env

    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.DEPLOY_HOST_SERVER }}
        username: ${{ secrets.DEPLOY_SERVER_USER }}
        ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}
        script: |
          mkdir -p ~/deploy
          cd ~/deploy
          git clone git@github.com:DrVeles/friends_bot.git . -b develop
          cp .env ~/deploy/.env
          docker-compose down
          docker-compose up -d --build
          docker ps
