name: Deploy to Server

on:
  push:
    branches:
      - develop
      - all-testing

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Copy environment variables to .env file
      run: |
        echo BOT_API_TOKEN=${{ secrets.BOT_API_TOKEN }} >> .env
        echo BOT_TOKEN=${{ secrets.BOT_TOKEN }} >> .env
        echo EDU_SCHOOL_LOGIN=${{ secrets.EDU_SCHOOL_LOGIN }} >> .env
        echo EDU_SCHOOL_PASSWORD=${{ secrets.EDU_SCHOOL_PASSWORD }} >> .env

        echo API_ADDRESS=${{ vars.API_ADDRESS }} >> .env
        echo API_PORT=${{ vars.API_PORT }} >> .env
        echo REDIS_HOST=${{ vars.REDIS_HOST }} >> .env
        echo REDIS_PORT=${{ vars.REDIS_PORT }} >> .env
        echo REDIS_DB=${{ vars.REDIS_DB }} >> .env

    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ vars.DEPLOY_HOST_SERVER }}
        username: ${{ vars.DEPLOY_SERVER_USER }}
        # password: ${{ secrets.DEPLOY_SERVER_PASSWORD }}
        script: |
          set -e
          echo "Deploying application..."
          mkdir -p ~/deploy
          cd ~/deploy
          git clone git@github.com:DrVeles/friends_bot.git . -b develop || git pull origin develop
          cp .env ~/deploy/.env
          docker-compose down
          docker-compose up -d --build
          docker ps
